package MTPLTariffRules

import hu.dbx.screek.model.*;
import hu.dbx.screek.model.State.States;
import hu.dbx.screek.model.facts.*;


rule "modify cubicCapacity to 0 (cubicCapacityNotDefined == true)"
    agenda-group "cleanup"
    no-loop 
	when
		$c1: Constant( name == "TC_SZEMELYGEPJARMU")
		$q : Quote( durationType == Constants.DT_HATAROZATLAN )
		$v : Vehicle( typeCode == $c1.value && 
					  cubicCapacityNotDefined == true )				  
			
	then
		$v.setCubicCapacity(0); //Visszaállítjuk a ccm értékét 0-ra		

end

rule "ModFactorok eltavolitas a sessionbol"
	agenda-group "cleanup"
	
	when
		$mf : ModFactor()
		
	then
		retract($mf);
end

rule "Atmeneti ParamDef(BASETARIFF-TEMP) eltavolitas a sessionbol"
	agenda-group "cleanup"
	
	when
		$p : ParamDef( key == "BASETARIFF-TEMP" )
		
	then
		retract($p);
end

rule "State-ek eltavolitas a sessionbol"
	agenda-group "cleanup"
	
	when
		$s : State( state != States.WF_CLEANUP &&
					state != States.AGENDA_CLEANUP_START &&
					state != States.AGENDA_CLEANUP_END)
		
	then
		retract($s);
end

rule "Message-ek eltavolitas a sessionbol"
	agenda-group "cleanup"
	
	when
		$q : Quote()
		$m : Message()
		$md : MessageDef(code == $m.code)
		
	then
		$m.setSeverity($md.getSeverity());
		$m.setDescription($md.getDescription());
		$q.addMessage($m);

		retract($m);
end

