package MTPLTariffRules

import hu.dbx.screek.model.facts.*;
import hu.dbx.screek.model.*;
import org.joda.time.DateTime;
import java.util.Date;

rule "setting groupedCollection flag"
    agenda-group "preprocess"
    lock-on-active
	when
		$p : PaymentMethodDef( paymentMethod == Constants.PM_BANKI_CSOPORTOS_BESZEDES )
		$q : Quote( paymentMethod == $p.paymentMethod)
		
	then
		modify( $q ) { setGroupedCollection( true ) };		
end

rule "insert vehicle-type-def contansts"
    agenda-group "preprocess"
	when
		$vt : VehicleTypeDef()
		not ( exists( Constant( name == $vt.constantName ) ) )
	then
		insert( new Constant($vt.getConstantName(), $vt.getTypeCode() ) );		
end

/*
rule "setting durationType (hatarozatlan)"
    agenda-group "preprocess"
    no-loop
	when
		$q : Quote( endDate == null )
	then
		modify ( $q ) {
			setDurationType( Constants.DT_HATAROZATLAN )
		}
end

rule "setting durationType (hatarozott)"
    agenda-group "preprocess"
    no-loop
	when
		$q : Quote( endDate != null )
	then
		modify ( $q ) {
			setDurationType( Constants.DT_HATAROZOTT )
		}
end
*/